<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            // Aceh

            ['id' => '1101', 'city_name' => 'KABUPATEN SIMEULUE', 'province_id' => '11'],
            ['id' => '1102', 'city_name' => 'KABUPATEN ACEH SINGKIL', 'province_id' => '11'],
            ['id' => '1103', 'city_name' => 'KABUPATEN ACEH SELATAN', 'province_id' => '11'],
            ['id' => '1104', 'city_name' => 'KABUPATEN ACEH TENGGARA', 'province_id' => '11'],
            ['id' => '1105', 'city_name' => 'KABUPATEN ACEH TIMUR', 'province_id' => '11'],
            ['id' => '1106', 'city_name' => 'KABUPATEN ACEH TENGAH', 'province_id' => '11'],
            ['id' => '1107', 'city_name' => 'KABUPATEN ACEH BARAT', 'province_id' => '11'],
            ['id' => '1108', 'city_name' => 'KABUPATEN ACEH BESAR', 'province_id' => '11'],
            ['id' => '1109', 'city_name' => 'KABUPATEN PIDIE', 'province_id' => '11'],
            ['id' => '1110', 'city_name' => 'KABUPATEN BIREUEN', 'province_id' => '11'],
            ['id' => '1111', 'city_name' => 'KABUPATEN ACEH UTARA', 'province_id' => '11'],
            ['id' => '1112', 'city_name' => 'KABUPATEN ACEH BARAT DAYA', 'province_id' => '11'],
            ['id' => '1113', 'city_name' => 'KABUPATEN GAYO LUES', 'province_id' => '11'],
            ['id' => '1114', 'city_name' => 'KABUPATEN ACEH TAMIANG', 'province_id' => '11'],
            ['id' => '1115', 'city_name' => 'KABUPATEN NAGAN RAYA', 'province_id' => '11'],
            ['id' => '1116', 'city_name' => 'KABUPATEN ACEH JAYA', 'province_id' => '11'],
            ['id' => '1117', 'city_name' => 'KABUPATEN BENER MERIAH', 'province_id' => '11'],
            ['id' => '1118', 'city_name' => 'KABUPATEN PIDIE JAYA', 'province_id' => '11'],
            ['id' => '1171', 'city_name' => 'KOTA BANDA ACEH', 'province_id' => '11'],
            ['id' => '1172', 'city_name' => 'KOTA SABANG', 'province_id' => '11'],
            ['id' => '1173', 'city_name' => 'KOTA LANGSA', 'province_id' => '11'],
            ['id' => '1174', 'city_name' => 'KOTA LHOKSEUMAWE', 'province_id' => '11'],
            ['id' => '1175', 'city_name' => 'KOTA SUBULUSSALAM', 'province_id' => '11'],
            ['id' => '1201', 'city_name' => 'KABUPATEN NIAS', 'province_id' => '12'],
            ['id' => '1202', 'city_name' => 'KABUPATEN MANDAILING NATAL', 'province_id' => '12'],
            ['id' => '1203', 'city_name' => 'KABUPATEN TAPANULI SELATAN', 'province_id' => '12'],
            ['id' => '1204', 'city_name' => 'KABUPATEN TAPANULI TENGAH', 'province_id' => '12'],
            ['id' => '1205', 'city_name' => 'KABUPATEN TAPANULI UTARA', 'province_id' => '12'],
            ['id' => '1206', 'city_name' => 'KABUPATEN TOBA SAMOSIR', 'province_id' => '12'],
            ['id' => '1207', 'city_name' => 'KABUPATEN LABUHAN BATU', 'province_id' => '12'],
            ['id' => '1208', 'city_name' => 'KABUPATEN ASAHAN', 'province_id' => '12'],
            ['id' => '1209', 'city_name' => 'KABUPATEN SIMALUNGUN', 'province_id' => '12'],
            ['id' => '1210', 'city_name' => 'KABUPATEN DAIRI', 'province_id' => '12'],
            ['id' => '1211', 'city_name' => 'KABUPATEN KARO', 'province_id' => '12'],
            ['id' => '1212', 'city_name' => 'KABUPATEN DELI SERDANG', 'province_id' => '12'],
            ['id' => '1213', 'city_name' => 'KABUPATEN LANGKAT', 'province_id' => '12'],
            ['id' => '1214', 'city_name' => 'KABUPATEN NIAS SELATAN', 'province_id' => '12'],
            ['id' => '1215', 'city_name' => 'KABUPATEN HUMBANG HASUNDUTAN', 'province_id' => '12'],
            ['id' => '1216', 'city_name' => 'KABUPATEN PAKPAK BHARAT', 'province_id' => '12'],
            ['id' => '1217', 'city_name' => 'KABUPATEN SAMOSIR', 'province_id' => '12'],
            ['id' => '1218', 'city_name' => 'KABUPATEN SERDANG BEDAGAI', 'province_id' => '12'],
            ['id' => '1219', 'city_name' => 'KABUPATEN BATU BARA', 'province_id' => '12'],
            ['id' => '1220', 'city_name' => 'KABUPATEN PADANG LAWAS UTARA', 'province_id' => '12'],
            ['id' => '1221', 'city_name' => 'KABUPATEN PADANG LAWAS', 'province_id' => '12'],
            ['id' => '1222', 'city_name' => 'KABUPATEN LABUHAN BATU SELATAN', 'province_id' => '12'],
            ['id' => '1223', 'city_name' => 'KABUPATEN LABUHAN BATU UTARA', 'province_id' => '12'],
            ['id' => '1224', 'city_name' => 'KABUPATEN NIAS UTARA', 'province_id' => '12'],
            ['id' => '1225', 'city_name' => 'KABUPATEN NIAS BARAT', 'province_id' => '12'],
            ['id' => '1271', 'city_name' => 'KOTA SIBOLGA', 'province_id' => '12'],
            ['id' => '1272', 'city_name' => 'KOTA TANJUNG BALAI', 'province_id' => '12'],
            ['id' => '1273', 'city_name' => 'KOTA PEMATANG SIANTAR', 'province_id' => '12'],
            ['id' => '1274', 'city_name' => 'KOTA TEBING TINGGI', 'province_id' => '12'],
            ['id' => '1275', 'city_name' => 'KOTA MEDAN', 'province_id' => '12'],
            ['id' => '1276', 'city_name' => 'KOTA BINJAI', 'province_id' => '12'],
            ['id' => '1277', 'city_name' => 'KOTA PADANGSIDIMPUAN', 'province_id' => '12'],
            ['id' => '1278', 'city_name' => 'KOTA GUNUNGSITOLI', 'province_id' => '12'],
            ['id' => '1301', 'city_name' => 'KABUPATEN KEPULAUAN MENTAWAI', 'province_id' => '13'],
            ['id' => '1302', 'city_name' => 'KABUPATEN PESISIR SELATAN', 'province_id' => '13'],
            ['id' => '1303', 'city_name' => 'KABUPATEN SOLOK', 'province_id' => '13'],
            ['id' => '1304', 'city_name' => 'KABUPATEN SIJUNJUNG', 'province_id' => '13'],
            ['id' => '1305', 'city_name' => 'KABUPATEN TANAH DATAR', 'province_id' => '13'],
            ['id' => '1306', 'city_name' => 'KABUPATEN PADANG PARIAMAN', 'province_id' => '13'],
            ['id' => '1307', 'city_name' => 'KABUPATEN AGAM', 'province_id' => '13'],
            ['id' => '1308', 'city_name' => 'KABUPATEN LIMA PULUH KOTA', 'province_id' => '13'],
            ['id' => '1309', 'city_name' => 'KABUPATEN PASAMAN', 'province_id' => '13'],
            ['id' => '1310', 'city_name' => 'KABUPATEN SOLOK SELATAN', 'province_id' => '13'],
            ['id' => '1311', 'city_name' => 'KABUPATEN DHARMASRAYA', 'province_id' => '13'],
            ['id' => '1312', 'city_name' => 'KABUPATEN PASAMAN BARAT', 'province_id' => '13'],
            ['id' => '1371', 'city_name' => 'KOTA PADANG', 'province_id' => '13'],
            ['id' => '1372', 'city_name' => 'KOTA SOLOK', 'province_id' => '13'],
            ['id' => '1373', 'city_name' => 'KOTA SAWAH LUNTO', 'province_id' => '13'],
            ['id' => '1374', 'city_name' => 'KOTA PADANG PANJANG', 'province_id' => '13'],
            ['id' => '1375', 'city_name' => 'KOTA BUKITTINGGI', 'province_id' => '13'],
            ['id' => '1376', 'city_name' => 'KOTA PAYAKUMBUH', 'province_id' => '13'],
            ['id' => '1377', 'city_name' => 'KOTA PARIAMAN', 'province_id' => '13'],
            ['id' => '1401', 'city_name' => 'KABUPATEN KUANTAN SINGINGI', 'province_id' => '14'],
            ['id' => '1402', 'city_name' => 'KABUPATEN INDRAGIRI HULU', 'province_id' => '14'],
            ['id' => '1403', 'city_name' => 'KABUPATEN INDRAGIRI HILIR', 'province_id' => '14'],
            ['id' => '1404', 'city_name' => 'KABUPATEN PELALAWAN', 'province_id' => '14'],
            ['id' => '1405', 'city_name' => 'KABUPATEN S I A K', 'province_id' => '14'],
            ['id' => '1406', 'city_name' => 'KABUPATEN KAMPAR', 'province_id' => '14'],
            ['id' => '1407', 'city_name' => 'KABUPATEN ROKAN HULU', 'province_id' => '14'],
            ['id' => '1408', 'city_name' => 'KABUPATEN BENGKALIS', 'province_id' => '14'],
            ['id' => '1409', 'city_name' => 'KABUPATEN ROKAN HILIR', 'province_id' => '14'],
            ['id' => '1410', 'city_name' => 'KABUPATEN KEPULAUAN MERANTI', 'province_id' => '14'],
            ['id' => '1471', 'city_name' => 'KOTA PEKANBARU', 'province_id' => '14'],
            ['id' => '1473', 'city_name' => 'KOTA D U M A I', 'province_id' => '14'],
            ['id' => '1501', 'city_name' => 'KABUPATEN KERINCI', 'province_id' => '15'],
            ['id' => '1502', 'city_name' => 'KABUPATEN MERANGIN', 'province_id' => '15'],
            ['id' => '1503', 'city_name' => 'KABUPATEN SAROLANGUN', 'province_id' => '15'],
            ['id' => '1504', 'city_name' => 'KABUPATEN BATANG HARI', 'province_id' => '15'],
            ['id' => '1505', 'city_name' => 'KABUPATEN MUARO JAMBI', 'province_id' => '15'],
            ['id' => '1506', 'city_name' => 'KABUPATEN TANJUNG JABUNG TIMUR', 'province_id' => '15'],
            ['id' => '1507', 'city_name' => 'KABUPATEN TANJUNG JABUNG BARAT', 'province_id' => '15'],
            ['id' => '1508', 'city_name' => 'KABUPATEN TEBO', 'province_id' => '15'],
            ['id' => '1509', 'city_name' => 'KABUPATEN BUNGO', 'province_id' => '15'],
            ['id' => '1571', 'city_name' => 'KOTA JAMBI', 'province_id' => '15'],
            ['id' => '1572', 'city_name' => 'KOTA SUNGAI PENUH', 'province_id' => '15'],
            ['id' => '1601', 'city_name' => 'KABUPATEN OGAN KOMERING ULU', 'province_id' => '16'],
            ['id' => '1602', 'city_name' => 'KABUPATEN OGAN KOMERING ILIR', 'province_id' => '16'],
            ['id' => '1603', 'city_name' => 'KABUPATEN MUARA ENIM', 'province_id' => '16'],
            ['id' => '1604', 'city_name' => 'KABUPATEN LAHAT', 'province_id' => '16'],
            ['id' => '1605', 'city_name' => 'KABUPATEN MUSI RAWAS', 'province_id' => '16'],
            ['id' => '1606', 'city_name' => 'KABUPATEN MUSI BANYUASIN', 'province_id' => '16'],
            ['id' => '1607', 'city_name' => 'KABUPATEN BANYU ASIN', 'province_id' => '16'],
            ['id' => '1608', 'city_name' => 'KABUPATEN OGAN KOMERING ULU SELATAN', 'province_id' => '16'],
            ['id' => '1609', 'city_name' => 'KABUPATEN OGAN KOMERING ULU TIMUR', 'province_id' => '16'],
            ['id' => '1610', 'city_name' => 'KABUPATEN OGAN ILIR', 'province_id' => '16'],
            ['id' => '1611', 'city_name' => 'KABUPATEN EMPAT LAWANG', 'province_id' => '16'],
            ['id' => '1612', 'city_name' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR', 'province_id' => '16'],
            ['id' => '1613', 'city_name' => 'KABUPATEN MUSI RAWAS UTARA', 'province_id' => '16'],
            ['id' => '1671', 'city_name' => 'KOTA PALEMBANG', 'province_id' => '16'],
            ['id' => '1672', 'city_name' => 'KOTA PRABUMULIH', 'province_id' => '16'],
            ['id' => '1673', 'city_name' => 'KOTA PAGAR ALAM', 'province_id' => '16'],
            ['id' => '1674', 'city_name' => 'KOTA LUBUKLINGGAU', 'province_id' => '16'],
            ['id' => '1701', 'city_name' => 'KABUPATEN BENGKULU SELATAN', 'province_id' => '17'],
            ['id' => '1702', 'city_name' => 'KABUPATEN REJANG LEBONG', 'province_id' => '17'],
            ['id' => '1703', 'city_name' => 'KABUPATEN BENGKULU UTARA', 'province_id' => '17'],
            ['id' => '1704', 'city_name' => 'KABUPATEN KAUR', 'province_id' => '17'],
            ['id' => '1705', 'city_name' => 'KABUPATEN SELUMA', 'province_id' => '17'],
            ['id' => '1706', 'city_name' => 'KABUPATEN MUKOMUKO', 'province_id' => '17'],
            ['id' => '1707', 'city_name' => 'KABUPATEN LEBONG', 'province_id' => '17'],
            ['id' => '1708', 'city_name' => 'KABUPATEN KEPAHIANG', 'province_id' => '17'],
            ['id' => '1709', 'city_name' => 'KABUPATEN BENGKULU TENGAH', 'province_id' => '17'],
            ['id' => '1771', 'city_name' => 'KOTA BENGKULU', 'province_id' => '17'],
            ['id' => '1801', 'city_name' => 'KABUPATEN LAMPUNG BARAT', 'province_id' => '18'],
            ['id' => '1802', 'city_name' => 'KABUPATEN TANGGAMUS', 'province_id' => '18'],
            ['id' => '1803', 'city_name' => 'KABUPATEN LAMPUNG SELATAN', 'province_id' => '18'],
            ['id' => '1804', 'city_name' => 'KABUPATEN LAMPUNG TIMUR', 'province_id' => '18'],
            ['id' => '1805', 'city_name' => 'KABUPATEN LAMPUNG TENGAH', 'province_id' => '18'],
            ['id' => '1806', 'city_name' => 'KABUPATEN LAMPUNG UTARA', 'province_id' => '18'],
            ['id' => '1807', 'city_name' => 'KABUPATEN WAY KANAN', 'province_id' => '18'],
            ['id' => '1808', 'city_name' => 'KABUPATEN TULANGBAWANG', 'province_id' => '18'],
            ['id' => '1809', 'city_name' => 'KABUPATEN PESAWARAN', 'province_id' => '18'],
            ['id' => '1810', 'city_name' => 'KABUPATEN PRINGSEWU', 'province_id' => '18'],
            ['id' => '1811', 'city_name' => 'KABUPATEN MESUJI', 'province_id' => '18'],
            ['id' => '1812', 'city_name' => 'KABUPATEN TULANG BAWANG BARAT', 'province_id' => '18'],
            ['id' => '1813', 'city_name' => 'KABUPATEN PESISIR BARAT', 'province_id' => '18'],
            ['id' => '1871', 'city_name' => 'KOTA BANDAR LAMPUNG', 'province_id' => '18'],
            ['id' => '1872', 'city_name' => 'KOTA METRO', 'province_id' => '18'],
            ['id' => '1901', 'city_name' => 'KABUPATEN BANGKA', 'province_id' => '19'],
            ['id' => '1902', 'city_name' => 'KABUPATEN BELITUNG', 'province_id' => '19'],
            ['id' => '1903', 'city_name' => 'KABUPATEN BANGKA BARAT', 'province_id' => '19'],
            ['id' => '1904', 'city_name' => 'KABUPATEN BANGKA TENGAH', 'province_id' => '19'],
            ['id' => '1905', 'city_name' => 'KABUPATEN BANGKA SELATAN', 'province_id' => '19'],
            ['id' => '1906', 'city_name' => 'KABUPATEN BELITUNG TIMUR', 'province_id' => '19'],
            ['id' => '1971', 'city_name' => 'KOTA PANGKAL PINANG', 'province_id' => '19'],
            ['id' => '2101', 'city_name' => 'KABUPATEN KARIMUN', 'province_id' => '21'],
            ['id' => '2102', 'city_name' => 'KABUPATEN BINTAN', 'province_id' => '21'],
            ['id' => '2103', 'city_name' => 'KABUPATEN NATUNA', 'province_id' => '21'],
            ['id' => '2104', 'city_name' => 'KABUPATEN LINGGA', 'province_id' => '21'],
            ['id' => '2105', 'city_name' => 'KABUPATEN KEPULAUAN ANAMBAS', 'province_id' => '21'],
            ['id' => '2171', 'city_name' => 'KOTA B A T A M', 'province_id' => '21'],
            ['id' => '2172', 'city_name' => 'KOTA TANJUNG PINANG', 'province_id' => '21'],
            ['id' => '3101', 'city_name' => 'KABUPATEN KEPULAUAN SERIBU', 'province_id' => '31'],
            ['id' => '3171', 'city_name' => 'KOTA JAKARTA SELATAN', 'province_id' => '31'],
            ['id' => '3172', 'city_name' => 'KOTA JAKARTA TIMUR', 'province_id' => '31'],
            ['id' => '3173', 'city_name' => 'KOTA JAKARTA PUSAT', 'province_id' => '31'],
            ['id' => '3174', 'city_name' => 'KOTA JAKARTA BARAT', 'province_id' => '31'],
            ['id' => '3175', 'city_name' => 'KOTA JAKARTA UTARA', 'province_id' => '31'],
            ['id' => '3201', 'city_name' => 'KABUPATEN BOGOR', 'province_id' => '32'],
            ['id' => '3202', 'city_name' => 'KABUPATEN SUKABUMI', 'province_id' => '32'],
            ['id' => '3203', 'city_name' => 'KABUPATEN CIANJUR', 'province_id' => '32'],
            ['id' => '3204', 'city_name' => 'KABUPATEN BANDUNG', 'province_id' => '32'],
            ['id' => '3205', 'city_name' => 'KABUPATEN GARUT', 'province_id' => '32'],
            ['id' => '3206', 'city_name' => 'KABUPATEN TASIKMALAYA', 'province_id' => '32'],
            ['id' => '3207', 'city_name' => 'KABUPATEN CIAMIS', 'province_id' => '32'],
            ['id' => '3208', 'city_name' => 'KABUPATEN KUNINGAN', 'province_id' => '32'],
            ['id' => '3209', 'city_name' => 'KABUPATEN CIREBON', 'province_id' => '32'],
            ['id' => '3210', 'city_name' => 'KABUPATEN MAJALENGKA', 'province_id' => '32'],
            ['id' => '3211', 'city_name' => 'KABUPATEN SUMEDANG', 'province_id' => '32'],
            ['id' => '3212', 'city_name' => 'KABUPATEN INDRAMAYU', 'province_id' => '32'],
            ['id' => '3213', 'city_name' => 'KABUPATEN SUBANG', 'province_id' => '32'],
            ['id' => '3214', 'city_name' => 'KABUPATEN PURWAKARTA', 'province_id' => '32'],
            ['id' => '3215', 'city_name' => 'KABUPATEN KARAWANG', 'province_id' => '32'],
            ['id' => '3216', 'city_name' => 'KABUPATEN BEKASI', 'province_id' => '32'],
            ['id' => '3217', 'city_name' => 'KABUPATEN BANDUNG BARAT', 'province_id' => '32'],
            ['id' => '3218', 'city_name' => 'KABUPATEN PANGANDARAN', 'province_id' => '32'],
            ['id' => '3271', 'city_name' => 'KOTA BOGOR', 'province_id' => '32'],
            ['id' => '3272', 'city_name' => 'KOTA SUKABUMI', 'province_id' => '32'],
            ['id' => '3273', 'city_name' => 'KOTA BANDUNG', 'province_id' => '32'],
            ['id' => '3274', 'city_name' => 'KOTA CIREBON', 'province_id' => '32'],
            ['id' => '3275', 'city_name' => 'KOTA BEKASI', 'province_id' => '32'],
            ['id' => '3276', 'city_name' => 'KOTA DEPOK', 'province_id' => '32'],
            ['id' => '3277', 'city_name' => 'KOTA CIMAHI', 'province_id' => '32'],
            ['id' => '3278', 'city_name' => 'KOTA TASIKMALAYA', 'province_id' => '32'],
            ['id' => '3279', 'city_name' => 'KOTA BANJAR', 'province_id' => '32'],
            ['id' => '3301', 'city_name' => 'KABUPATEN CILACAP', 'province_id' => '33'],
            ['id' => '3302', 'city_name' => 'KABUPATEN BANYUMAS', 'province_id' => '33'],
            ['id' => '3303', 'city_name' => 'KABUPATEN PURBALINGGA', 'province_id' => '33'],
            ['id' => '3304', 'city_name' => 'KABUPATEN BANJARNEGARA', 'province_id' => '33'],
            ['id' => '3305', 'city_name' => 'KABUPATEN KEBUMEN', 'province_id' => '33'],
            ['id' => '3306', 'city_name' => 'KABUPATEN PURWOREJO', 'province_id' => '33'],
            ['id' => '3307', 'city_name' => 'KABUPATEN WONOSOBO', 'province_id' => '33'],
            ['id' => '3308', 'city_name' => 'KABUPATEN MAGELANG', 'province_id' => '33'],
            ['id' => '3309', 'city_name' => 'KABUPATEN BOYOLALI', 'province_id' => '33'],
            ['id' => '3310', 'city_name' => 'KABUPATEN KLATEN', 'province_id' => '33'],
            ['id' => '3311', 'city_name' => 'KABUPATEN SUKOHARJO', 'province_id' => '33'],
            ['id' => '3312', 'city_name' => 'KABUPATEN WONOGIRI', 'province_id' => '33'],
            ['id' => '3313', 'city_name' => 'KABUPATEN KARANGANYAR', 'province_id' => '33'],
            ['id' => '3314', 'city_name' => 'KABUPATEN SRAGEN', 'province_id' => '33'],
            ['id' => '3315', 'city_name' => 'KABUPATEN GROBOGAN', 'province_id' => '33'],
            ['id' => '3316', 'city_name' => 'KABUPATEN BLORA', 'province_id' => '33'],
            ['id' => '3317', 'city_name' => 'KABUPATEN REMBANG', 'province_id' => '33'],
            ['id' => '3318', 'city_name' => 'KABUPATEN PATI', 'province_id' => '33'],
            ['id' => '3319', 'city_name' => 'KABUPATEN KUDUS', 'province_id' => '33'],
            ['id' => '3320', 'city_name' => 'KABUPATEN JEPARA', 'province_id' => '33'],
            ['id' => '3321', 'city_name' => 'KABUPATEN DEMAK', 'province_id' => '33'],
            ['id' => '3322', 'city_name' => 'KABUPATEN SEMARANG', 'province_id' => '33'],
            ['id' => '3323', 'city_name' => 'KABUPATEN TEMANGGUNG', 'province_id' => '33'],
            ['id' => '3324', 'city_name' => 'KABUPATEN KENDAL', 'province_id' => '33'],
            ['id' => '3325', 'city_name' => 'KABUPATEN BATANG', 'province_id' => '33'],
            ['id' => '3326', 'city_name' => 'KABUPATEN PEKALONGAN', 'province_id' => '33'],
            ['id' => '3327', 'city_name' => 'KABUPATEN PEMALANG', 'province_id' => '33'],
            ['id' => '3328', 'city_name' => 'KABUPATEN TEGAL', 'province_id' => '33'],
            ['id' => '3329', 'city_name' => 'KABUPATEN BREBES', 'province_id' => '33'],
            ['id' => '3371', 'city_name' => 'KOTA MAGELANG', 'province_id' => '33'],
            ['id' => '3372', 'city_name' => 'KOTA SURAKARTA', 'province_id' => '33'],
            ['id' => '3373', 'city_name' => 'KOTA SALATIGA', 'province_id' => '33'],
            ['id' => '3374', 'city_name' => 'KOTA SEMARANG', 'province_id' => '33'],
            ['id' => '3375', 'city_name' => 'KOTA PEKALONGAN', 'province_id' => '33'],
            ['id' => '3376', 'city_name' => 'KOTA TEGAL', 'province_id' => '33'],
            ['id' => '3401', 'city_name' => 'KABUPATEN KULON PROGO', 'province_id' => '34'],
            ['id' => '3402', 'city_name' => 'KABUPATEN BANTUL', 'province_id' => '34'],
            ['id' => '3403', 'city_name' => 'KABUPATEN GUNUNG KIDUL', 'province_id' => '34'],
            ['id' => '3404', 'city_name' => 'KABUPATEN SLEMAN', 'province_id' => '34'],
            ['id' => '3471', 'city_name' => 'KOTA YOGYAKARTA', 'province_id' => '34'],
            ['id' => '3501', 'city_name' => 'KABUPATEN PACITAN', 'province_id' => '35'],
            ['id' => '3502', 'city_name' => 'KABUPATEN PONOROGO', 'province_id' => '35'],
            ['id' => '3503', 'city_name' => 'KABUPATEN TRENGGALEK', 'province_id' => '35'],
            ['id' => '3504', 'city_name' => 'KABUPATEN TULUNGAGUNG', 'province_id' => '35'],
            ['id' => '3505', 'city_name' => 'KABUPATEN BLITAR', 'province_id' => '35'],
            ['id' => '3506', 'city_name' => 'KABUPATEN KEDIRI', 'province_id' => '35'],
            ['id' => '3507', 'city_name' => 'KABUPATEN MALANG', 'province_id' => '35'],
            ['id' => '3508', 'city_name' => 'KABUPATEN LUMAJANG', 'province_id' => '35'],
            ['id' => '3509', 'city_name' => 'KABUPATEN JEMBER', 'province_id' => '35'],
            ['id' => '3510', 'city_name' => 'KABUPATEN BANYUWANGI', 'province_id' => '35'],
            ['id' => '3511', 'city_name' => 'KABUPATEN BONDOWOSO', 'province_id' => '35'],
            ['id' => '3512', 'city_name' => 'KABUPATEN SITUBONDO', 'province_id' => '35'],
            ['id' => '3513', 'city_name' => 'KABUPATEN PROBOLINGGO', 'province_id' => '35'],
            ['id' => '3514', 'city_name' => 'KABUPATEN PASURUAN', 'province_id' => '35'],
            ['id' => '3515', 'city_name' => 'KABUPATEN SIDOARJO', 'province_id' => '35'],
            ['id' => '3516', 'city_name' => 'KABUPATEN MOJOKERTO', 'province_id' => '35'],
            ['id' => '3517', 'city_name' => 'KABUPATEN JOMBANG', 'province_id' => '35'],
            ['id' => '3518', 'city_name' => 'KABUPATEN NGANJUK', 'province_id' => '35'],
            ['id' => '3519', 'city_name' => 'KABUPATEN MADIUN', 'province_id' => '35'],
            ['id' => '3520', 'city_name' => 'KABUPATEN MAGETAN', 'province_id' => '35'],
            ['id' => '3521', 'city_name' => 'KABUPATEN NGAWI', 'province_id' => '35'],
            ['id' => '3522', 'city_name' => 'KABUPATEN BOJONEGORO', 'province_id' => '35'],
            ['id' => '3523', 'city_name' => 'KABUPATEN TUBAN', 'province_id' => '35'],
            ['id' => '3524', 'city_name' => 'KABUPATEN LAMONGAN', 'province_id' => '35'],
            ['id' => '3525', 'city_name' => 'KABUPATEN GRESIK', 'province_id' => '35'],
            ['id' => '3526', 'city_name' => 'KABUPATEN BANGKALAN', 'province_id' => '35'],
            ['id' => '3527', 'city_name' => 'KABUPATEN SAMPANG', 'province_id' => '35'],
            ['id' => '3528', 'city_name' => 'KABUPATEN PAMEKASAN', 'province_id' => '35'],
            ['id' => '3529', 'city_name' => 'KABUPATEN SUMENEP', 'province_id' => '35'],
            ['id' => '3571', 'city_name' => 'KOTA KEDIRI', 'province_id' => '35'],
            ['id' => '3572', 'city_name' => 'KOTA BLITAR', 'province_id' => '35'],
            ['id' => '3573', 'city_name' => 'KOTA MALANG', 'province_id' => '35'],
            ['id' => '3574', 'city_name' => 'KOTA PROBOLINGGO', 'province_id' => '35'],
            ['id' => '3575', 'city_name' => 'KOTA PASURUAN', 'province_id' => '35'],
            ['id' => '3576', 'city_name' => 'KOTA MOJOKERTO', 'province_id' => '35'],
            ['id' => '3577', 'city_name' => 'KOTA MADIUN', 'province_id' => '35'],
            ['id' => '3578', 'city_name' => 'KOTA SURABAYA', 'province_id' => '35'],
            ['id' => '3579', 'city_name' => 'KOTA BATU', 'province_id' => '35'],
            ['id' => '3601', 'city_name' => 'KABUPATEN PANDEGLANG', 'province_id' => '36'],
            ['id' => '3602', 'city_name' => 'KABUPATEN LEBAK', 'province_id' => '36'],
            ['id' => '3603', 'city_name' => 'KABUPATEN TANGERANG', 'province_id' => '36'],
            ['id' => '3604', 'city_name' => 'KABUPATEN SERANG', 'province_id' => '36'],
            ['id' => '3671', 'city_name' => 'KOTA TANGERANG', 'province_id' => '36'],
            ['id' => '3672', 'city_name' => 'KOTA CILEGON', 'province_id' => '36'],
            ['id' => '3673', 'city_name' => 'KOTA SERANG', 'province_id' => '36'],
            ['id' => '3674', 'city_name' => 'KOTA TANGERANG SELATAN', 'province_id' => '36'],
            ['id' => '5101', 'city_name' => 'KABUPATEN JEMBRANA', 'province_id' => '51'],
            ['id' => '5102', 'city_name' => 'KABUPATEN TABANAN', 'province_id' => '51'],
            ['id' => '5103', 'city_name' => 'KABUPATEN BADUNG', 'province_id' => '51'],
            ['id' => '5104', 'city_name' => 'KABUPATEN GIANYAR', 'province_id' => '51'],
            ['id' => '5105', 'city_name' => 'KABUPATEN KLUNGKUNG', 'province_id' => '51'],
            ['id' => '5106', 'city_name' => 'KABUPATEN BANGLI', 'province_id' => '51'],
            ['id' => '5107', 'city_name' => 'KABUPATEN KARANG ASEM', 'province_id' => '51'],
            ['id' => '5108', 'city_name' => 'KABUPATEN BULELENG', 'province_id' => '51'],
            ['id' => '5171', 'city_name' => 'KOTA DENPASAR', 'province_id' => '51'],
            ['id' => '5201', 'city_name' => 'KABUPATEN LOMBOK BARAT', 'province_id' => '52'],
            ['id' => '5202', 'city_name' => 'KABUPATEN LOMBOK TENGAH', 'province_id' => '52'],
            ['id' => '5203', 'city_name' => 'KABUPATEN LOMBOK TIMUR', 'province_id' => '52'],
            ['id' => '5204', 'city_name' => 'KABUPATEN SUMBAWA', 'province_id' => '52'],
            ['id' => '5205', 'city_name' => 'KABUPATEN DOMPU', 'province_id' => '52'],
            ['id' => '5206', 'city_name' => 'KABUPATEN BIMA', 'province_id' => '52'],
            ['id' => '5207', 'city_name' => 'KABUPATEN SUMBAWA BARAT', 'province_id' => '52'],
            ['id' => '5208', 'city_name' => 'KABUPATEN LOMBOK UTARA', 'province_id' => '52'],
            ['id' => '5271', 'city_name' => 'KOTA MATARAM', 'province_id' => '52'],
            ['id' => '5272', 'city_name' => 'KOTA BIMA', 'province_id' => '52'],
            ['id' => '5301', 'city_name' => 'KABUPATEN SUMBA BARAT', 'province_id' => '53'],
            ['id' => '5302', 'city_name' => 'KABUPATEN SUMBA TIMUR', 'province_id' => '53'],
            ['id' => '5303', 'city_name' => 'KABUPATEN KUPANG', 'province_id' => '53'],
            ['id' => '5304', 'city_name' => 'KABUPATEN TIMOR TENGAH SELATAN', 'province_id' => '53'],
            ['id' => '5305', 'city_name' => 'KABUPATEN TIMOR TENGAH UTARA', 'province_id' => '53'],
            ['id' => '5306', 'city_name' => 'KABUPATEN BELU', 'province_id' => '53'],
            ['id' => '5307', 'city_name' => 'KABUPATEN ALOR', 'province_id' => '53'],
            ['id' => '5308', 'city_name' => 'KABUPATEN LEMBATA', 'province_id' => '53'],
            ['id' => '5309', 'city_name' => 'KABUPATEN FLORES TIMUR', 'province_id' => '53'],
            ['id' => '5310', 'city_name' => 'KABUPATEN SIKKA', 'province_id' => '53'],
            ['id' => '5311', 'city_name' => 'KABUPATEN ENDE', 'province_id' => '53'],
            ['id' => '5312', 'city_name' => 'KABUPATEN NGADA', 'province_id' => '53'],
            ['id' => '5313', 'city_name' => 'KABUPATEN MANGGARAI', 'province_id' => '53'],
            ['id' => '5314', 'city_name' => 'KABUPATEN ROTE NDAO', 'province_id' => '53'],
            ['id' => '5315', 'city_name' => 'KABUPATEN MANGGARAI BARAT', 'province_id' => '53'],
            ['id' => '5316', 'city_name' => 'KABUPATEN SUMBA TENGAH', 'province_id' => '53'],
            ['id' => '5317', 'city_name' => 'KABUPATEN SUMBA BARAT DAYA', 'province_id' => '53'],
            ['id' => '5318', 'city_name' => 'KABUPATEN NAGEKEO', 'province_id' => '53'],
            ['id' => '5319', 'city_name' => 'KABUPATEN MANGGARAI TIMUR', 'province_id' => '53'],
            ['id' => '5320', 'city_name' => 'KABUPATEN SABU RAIJUA', 'province_id' => '53'],
            ['id' => '5321', 'city_name' => 'KABUPATEN MALAKA', 'province_id' => '53'],
            ['id' => '5371', 'city_name' => 'KOTA KUPANG', 'province_id' => '53'],
            ['id' => '6101', 'city_name' => 'KABUPATEN SAMBAS', 'province_id' => '61'],
            ['id' => '6102', 'city_name' => 'KABUPATEN BENGKAYANG', 'province_id' => '61'],
            ['id' => '6103', 'city_name' => 'KABUPATEN LANDAK', 'province_id' => '61'],
            ['id' => '6104', 'city_name' => 'KABUPATEN MEMPAWAH', 'province_id' => '61'],
            ['id' => '6105', 'city_name' => 'KABUPATEN SANGGAU', 'province_id' => '61'],
            ['id' => '6106', 'city_name' => 'KABUPATEN KETAPANG', 'province_id' => '61'],
            ['id' => '6107', 'city_name' => 'KABUPATEN SINTANG', 'province_id' => '61'],
            ['id' => '6108', 'city_name' => 'KABUPATEN KAPUAS HULU', 'province_id' => '61'],
            ['id' => '6109', 'city_name' => 'KABUPATEN SEKADAU', 'province_id' => '61'],
            ['id' => '6110', 'city_name' => 'KABUPATEN MELAWI', 'province_id' => '61'],
            ['id' => '6111', 'city_name' => 'KABUPATEN KAYONG UTARA', 'province_id' => '61'],
            ['id' => '6112', 'city_name' => 'KABUPATEN KUBU RAYA', 'province_id' => '61'],
            ['id' => '6171', 'city_name' => 'KOTA PONTIANAK', 'province_id' => '61'],
            ['id' => '6172', 'city_name' => 'KOTA SINGKAWANG', 'province_id' => '61'],
            ['id' => '6201', 'city_name' => 'KABUPATEN KOTAWARINGIN BARAT', 'province_id' => '62'],
            ['id' => '6202', 'city_name' => 'KABUPATEN KOTAWARINGIN TIMUR', 'province_id' => '62'],
            ['id' => '6203', 'city_name' => 'KABUPATEN KAPUAS', 'province_id' => '62'],
            ['id' => '6204', 'city_name' => 'KABUPATEN BARITO SELATAN', 'province_id' => '62'],
            ['id' => '6205', 'city_name' => 'KABUPATEN BARITO UTARA', 'province_id' => '62'],
            ['id' => '6206', 'city_name' => 'KABUPATEN SUKAMARA', 'province_id' => '62'],
            ['id' => '6207', 'city_name' => 'KABUPATEN LAMANDAU', 'province_id' => '62'],
            ['id' => '6208', 'city_name' => 'KABUPATEN SERUYAN', 'province_id' => '62'],
            ['id' => '6209', 'city_name' => 'KABUPATEN KATINGAN', 'province_id' => '62'],
            ['id' => '6210', 'city_name' => 'KABUPATEN PULANG PISAU', 'province_id' => '62'],
            ['id' => '6211', 'city_name' => 'KABUPATEN GUNUNG MAS', 'province_id' => '62'],
            ['id' => '6212', 'city_name' => 'KABUPATEN BARITO TIMUR', 'province_id' => '62'],
            ['id' => '6213', 'city_name' => 'KABUPATEN MURUNG RAYA', 'province_id' => '62'],
            ['id' => '6271', 'city_name' => 'KOTA PALANGKA RAYA', 'province_id' => '62'],
            ['id' => '6301', 'city_name' => 'KABUPATEN TANAH LAUT', 'province_id' => '63'],
            ['id' => '6302', 'city_name' => 'KABUPATEN KOTA BARU', 'province_id' => '63'],
            ['id' => '6303', 'city_name' => 'KABUPATEN BANJAR', 'province_id' => '63'],
            ['id' => '6304', 'city_name' => 'KABUPATEN BARITO KUALA', 'province_id' => '63'],
            ['id' => '6305', 'city_name' => 'KABUPATEN TAPIN', 'province_id' => '63'],
            ['id' => '6306', 'city_name' => 'KABUPATEN HULU SUNGAI SELATAN', 'province_id' => '63'],
            ['id' => '6307', 'city_name' => 'KABUPATEN HULU SUNGAI TENGAH', 'province_id' => '63'],
            ['id' => '6308', 'city_name' => 'KABUPATEN HULU SUNGAI UTARA', 'province_id' => '63'],
            ['id' => '6309', 'city_name' => 'KABUPATEN TABALONG', 'province_id' => '63'],
            ['id' => '6310', 'city_name' => 'KABUPATEN TANAH BUMBU', 'province_id' => '63'],
            ['id' => '6311', 'city_name' => 'KABUPATEN BALANGAN', 'province_id' => '63'],
            ['id' => '6371', 'city_name' => 'KOTA BANJARMASIN', 'province_id' => '63'],
            ['id' => '6372', 'city_name' => 'KOTA BANJAR BARU', 'province_id' => '63'],
            ['id' => '6401', 'city_name' => 'KABUPATEN PASER', 'province_id' => '64'],
            ['id' => '6402', 'city_name' => 'KABUPATEN KUTAI BARAT', 'province_id' => '64'],
            ['id' => '6403', 'city_name' => 'KABUPATEN KUTAI KARTANEGARA', 'province_id' => '64'],
            ['id' => '6404', 'city_name' => 'KABUPATEN KUTAI TIMUR', 'province_id' => '64'],
            ['id' => '6405', 'city_name' => 'KABUPATEN BERAU', 'province_id' => '64'],
            ['id' => '6409', 'city_name' => 'KABUPATEN PENAJAM PASER UTARA', 'province_id' => '64'],
            ['id' => '6411', 'city_name' => 'KABUPATEN MAHAKAM HULU', 'province_id' => '64'],
            ['id' => '6471', 'city_name' => 'KOTA BALIKPAPAN', 'province_id' => '64'],
            ['id' => '6472', 'city_name' => 'KOTA SAMARINDA', 'province_id' => '64'],
            ['id' => '6474', 'city_name' => 'KOTA BONTANG', 'province_id' => '64'],
            ['id' => '6501', 'city_name' => 'KABUPATEN MALINAU', 'province_id' => '65'],
            ['id' => '6502', 'city_name' => 'KABUPATEN BULUNGAN', 'province_id' => '65'],
            ['id' => '6503', 'city_name' => 'KABUPATEN TANA TIDUNG', 'province_id' => '65'],
            ['id' => '6504', 'city_name' => 'KABUPATEN NUNUKAN', 'province_id' => '65'],
            ['id' => '6571', 'city_name' => 'KOTA TARAKAN', 'province_id' => '65'],
            ['id' => '7101', 'city_name' => 'KABUPATEN BOLAANG MONGONDOW', 'province_id' => '71'],
            ['id' => '7102', 'city_name' => 'KABUPATEN MINAHASA', 'province_id' => '71'],
            ['id' => '7103', 'city_name' => 'KABUPATEN KEPULAUAN SANGIHE', 'province_id' => '71'],
            ['id' => '7104', 'city_name' => 'KABUPATEN KEPULAUAN TALAUD', 'province_id' => '71'],
            ['id' => '7105', 'city_name' => 'KABUPATEN MINAHASA SELATAN', 'province_id' => '71'],
            ['id' => '7106', 'city_name' => 'KABUPATEN MINAHASA UTARA', 'province_id' => '71'],
            ['id' => '7107', 'city_name' => 'KABUPATEN BOLAANG MONGONDOW UTARA', 'province_id' => '71'],
            ['id' => '7108', 'city_name' => 'KABUPATEN SIAU TAGULANDANG BIARO', 'province_id' => '71'],
            ['id' => '7109', 'city_name' => 'KABUPATEN MINAHASA TENGGARA', 'province_id' => '71'],
            ['id' => '7110', 'city_name' => 'KABUPATEN BOLAANG MONGONDOW SELATAN', 'province_id' => '71'],
            ['id' => '7111', 'city_name' => 'KABUPATEN BOLAANG MONGONDOW TIMUR', 'province_id' => '71'],
            ['id' => '7171', 'city_name' => 'KOTA MANADO', 'province_id' => '71'],
            ['id' => '7172', 'city_name' => 'KOTA BITUNG', 'province_id' => '71'],
            ['id' => '7173', 'city_name' => 'KOTA TOMOHON', 'province_id' => '71'],
            ['id' => '7174', 'city_name' => 'KOTA KOTAMOBAGU', 'province_id' => '71'],
            ['id' => '7201', 'city_name' => 'KABUPATEN BANGGAI KEPULAUAN', 'province_id' => '72'],
            ['id' => '7202', 'city_name' => 'KABUPATEN BANGGAI', 'province_id' => '72'],
            ['id' => '7203', 'city_name' => 'KABUPATEN MOROWALI', 'province_id' => '72'],
            ['id' => '7204', 'city_name' => 'KABUPATEN POSO', 'province_id' => '72'],
            ['id' => '7205', 'city_name' => 'KABUPATEN DONGGALA', 'province_id' => '72'],
            ['id' => '7206', 'city_name' => 'KABUPATEN TOLI-TOLI', 'province_id' => '72'],
            ['id' => '7207', 'city_name' => 'KABUPATEN BUOL', 'province_id' => '72'],
            ['id' => '7208', 'city_name' => 'KABUPATEN PARIGI MOUTONG', 'province_id' => '72'],
            ['id' => '7209', 'city_name' => 'KABUPATEN TOJO UNA-UNA', 'province_id' => '72'],
            ['id' => '7210', 'city_name' => 'KABUPATEN SIGI', 'province_id' => '72'],
            ['id' => '7211', 'city_name' => 'KABUPATEN BANGGAI LAUT', 'province_id' => '72'],
            ['id' => '7212', 'city_name' => 'KABUPATEN MOROWALI UTARA', 'province_id' => '72'],
            ['id' => '7271', 'city_name' => 'KOTA PALU', 'province_id' => '72'],
            ['id' => '7301', 'city_name' => 'KABUPATEN KEPULAUAN SELAYAR', 'province_id' => '73'],
            ['id' => '7302', 'city_name' => 'KABUPATEN BULUKUMBA', 'province_id' => '73'],
            ['id' => '7303', 'city_name' => 'KABUPATEN BANTAENG', 'province_id' => '73'],
            ['id' => '7304', 'city_name' => 'KABUPATEN JENEPONTO', 'province_id' => '73'],
            ['id' => '7305', 'city_name' => 'KABUPATEN TAKALAR', 'province_id' => '73'],
            ['id' => '7306', 'city_name' => 'KABUPATEN GOWA', 'province_id' => '73'],
            ['id' => '7307', 'city_name' => 'KABUPATEN SINJAI', 'province_id' => '73'],
            ['id' => '7308', 'city_name' => 'KABUPATEN MAROS', 'province_id' => '73'],
            ['id' => '7309', 'city_name' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN', 'province_id' => '73'],
            ['id' => '7310', 'city_name' => 'KABUPATEN BARRU', 'province_id' => '73'],
            ['id' => '7311', 'city_name' => 'KABUPATEN BONE', 'province_id' => '73'],
            ['id' => '7312', 'city_name' => 'KABUPATEN SOPPENG', 'province_id' => '73'],
            ['id' => '7313', 'city_name' => 'KABUPATEN WAJO', 'province_id' => '73'],
            ['id' => '7314', 'city_name' => 'KABUPATEN SIDENRENG RAPPANG', 'province_id' => '73'],
            ['id' => '7315', 'city_name' => 'KABUPATEN PINRANG', 'province_id' => '73'],
            ['id' => '7316', 'city_name' => 'KABUPATEN ENREKANG', 'province_id' => '73'],
            ['id' => '7317', 'city_name' => 'KABUPATEN LUWU', 'province_id' => '73'],
            ['id' => '7318', 'city_name' => 'KABUPATEN TANA TORAJA', 'province_id' => '73'],
            ['id' => '7322', 'city_name' => 'KABUPATEN LUWU UTARA', 'province_id' => '73'],
            ['id' => '7325', 'city_name' => 'KABUPATEN LUWU TIMUR', 'province_id' => '73'],
            ['id' => '7326', 'city_name' => 'KABUPATEN TORAJA UTARA', 'province_id' => '73'],
            ['id' => '7371', 'city_name' => 'KOTA MAKASSAR', 'province_id' => '73'],
            ['id' => '7372', 'city_name' => 'KOTA PAREPARE', 'province_id' => '73'],
            ['id' => '7373', 'city_name' => 'KOTA PALOPO', 'province_id' => '73'],
            ['id' => '7401', 'city_name' => 'KABUPATEN BUTON', 'province_id' => '74'],
            ['id' => '7402', 'city_name' => 'KABUPATEN MUNA', 'province_id' => '74'],
            ['id' => '7403', 'city_name' => 'KABUPATEN KONAWE', 'province_id' => '74'],
            ['id' => '7404', 'city_name' => 'KABUPATEN KOLAKA', 'province_id' => '74'],
            ['id' => '7405', 'city_name' => 'KABUPATEN KONAWE SELATAN', 'province_id' => '74'],
            ['id' => '7406', 'city_name' => 'KABUPATEN BOMBANA', 'province_id' => '74'],
            ['id' => '7407', 'city_name' => 'KABUPATEN WAKATOBI', 'province_id' => '74'],
            ['id' => '7408', 'city_name' => 'KABUPATEN KOLAKA UTARA', 'province_id' => '74'],
            ['id' => '7409', 'city_name' => 'KABUPATEN BUTON UTARA', 'province_id' => '74'],
            ['id' => '7410', 'city_name' => 'KABUPATEN KONAWE UTARA', 'province_id' => '74'],
            ['id' => '7411', 'city_name' => 'KABUPATEN KOLAKA TIMUR', 'province_id' => '74'],
            ['id' => '7412', 'city_name' => 'KABUPATEN KONAWE KEPULAUAN', 'province_id' => '74'],
            ['id' => '7413', 'city_name' => 'KABUPATEN MUNA BARAT', 'province_id' => '74'],
            ['id' => '7414', 'city_name' => 'KABUPATEN BUTON TENGAH', 'province_id' => '74'],
            ['id' => '7415', 'city_name' => 'KABUPATEN BUTON SELATAN', 'province_id' => '74'],
            ['id' => '7471', 'city_name' => 'KOTA KENDARI', 'province_id' => '74'],
            ['id' => '7472', 'city_name' => 'KOTA BAUBAU', 'province_id' => '74'],
            ['id' => '7501', 'city_name' => 'KABUPATEN BOALEMO', 'province_id' => '75'],
            ['id' => '7502', 'city_name' => 'KABUPATEN GORONTALO', 'province_id' => '75'],
            ['id' => '7503', 'city_name' => 'KABUPATEN POHUWATO', 'province_id' => '75'],
            ['id' => '7504', 'city_name' => 'KABUPATEN BONE BOLANGO', 'province_id' => '75'],
            ['id' => '7505', 'city_name' => 'KABUPATEN GORONTALO UTARA', 'province_id' => '75'],
            ['id' => '7571', 'city_name' => 'KOTA GORONTALO', 'province_id' => '75'],
            ['id' => '7601', 'city_name' => 'KABUPATEN MAJENE', 'province_id' => '76'],
            ['id' => '7602', 'city_name' => 'KABUPATEN POLEWALI MANDAR', 'province_id' => '76'],
            ['id' => '7603', 'city_name' => 'KABUPATEN MAMASA', 'province_id' => '76'],
            ['id' => '7604', 'city_name' => 'KABUPATEN MAMUJU', 'province_id' => '76'],
            ['id' => '7605', 'city_name' => 'KABUPATEN MAMUJU UTARA', 'province_id' => '76'],
            ['id' => '7606', 'city_name' => 'KABUPATEN MAMUJU TENGAH', 'province_id' => '76'],
            ['id' => '8101', 'city_name' => 'KABUPATEN MALUKU TENGGARA BARAT', 'province_id' => '81'],
            ['id' => '8102', 'city_name' => 'KABUPATEN MALUKU TENGGARA', 'province_id' => '81'],
            ['id' => '8103', 'city_name' => 'KABUPATEN MALUKU TENGAH', 'province_id' => '81'],
            ['id' => '8104', 'city_name' => 'KABUPATEN BURU', 'province_id' => '81'],
            ['id' => '8105', 'city_name' => 'KABUPATEN KEPULAUAN ARU', 'province_id' => '81'],
            ['id' => '8106', 'city_name' => 'KABUPATEN SERAM BAGIAN BARAT', 'province_id' => '81'],
            ['id' => '8107', 'city_name' => 'KABUPATEN SERAM BAGIAN TIMUR', 'province_id' => '81'],
            ['id' => '8108', 'city_name' => 'KABUPATEN MALUKU BARAT DAYA', 'province_id' => '81'],
            ['id' => '8109', 'city_name' => 'KABUPATEN BURU SELATAN', 'province_id' => '81'],
            ['id' => '8171', 'city_name' => 'KOTA AMBON', 'province_id' => '81'],
            ['id' => '8172', 'city_name' => 'KOTA TUAL', 'province_id' => '81'],
            ['id' => '8201', 'city_name' => 'KABUPATEN HALMAHERA BARAT', 'province_id' => '82'],
            ['id' => '8202', 'city_name' => 'KABUPATEN HALMAHERA TENGAH', 'province_id' => '82'],
            ['id' => '8203', 'city_name' => 'KABUPATEN KEPULAUAN SULA', 'province_id' => '82'],
            ['id' => '8204', 'city_name' => 'KABUPATEN HALMAHERA SELATAN', 'province_id' => '82'],
            ['id' => '8205', 'city_name' => 'KABUPATEN HALMAHERA UTARA', 'province_id' => '82'],
            ['id' => '8206', 'city_name' => 'KABUPATEN HALMAHERA TIMUR', 'province_id' => '82'],
            ['id' => '8207', 'city_name' => 'KABUPATEN PULAU MOROTAI', 'province_id' => '82'],
            ['id' => '8208', 'city_name' => 'KABUPATEN PULAU TALIABU', 'province_id' => '82'],
            ['id' => '8271', 'city_name' => 'KOTA TERNATE', 'province_id' => '82'],
            ['id' => '8272', 'city_name' => 'KOTA TIDORE KEPULAUAN', 'province_id' => '82'],
            ['id' => '9101', 'city_name' => 'KABUPATEN FAKFAK', 'province_id' => '91'],
            ['id' => '9102', 'city_name' => 'KABUPATEN KAIMANA', 'province_id' => '91'],
            ['id' => '9103', 'city_name' => 'KABUPATEN TELUK WONDAMA', 'province_id' => '91'],
            ['id' => '9104', 'city_name' => 'KABUPATEN TELUK BINTUNI', 'province_id' => '91'],
            ['id' => '9105', 'city_name' => 'KABUPATEN MANOKWARI', 'province_id' => '91'],
            ['id' => '9106', 'city_name' => 'KABUPATEN SORONG SELATAN', 'province_id' => '91'],
            ['id' => '9107', 'city_name' => 'KABUPATEN SORONG', 'province_id' => '91'],
            ['id' => '9108', 'city_name' => 'KABUPATEN RAJA AMPAT', 'province_id' => '91'],
            ['id' => '9109', 'city_name' => 'KABUPATEN TAMBRAUW', 'province_id' => '91'],
            ['id' => '9110', 'city_name' => 'KABUPATEN MAYBRAT', 'province_id' => '91'],
            ['id' => '9111', 'city_name' => 'KABUPATEN MANOKWARI SELATAN', 'province_id' => '91'],
            ['id' => '9112', 'city_name' => 'KABUPATEN PEGUNUNGAN ARFAK', 'province_id' => '91'],
            ['id' => '9171', 'city_name' => 'KOTA SORONG', 'province_id' => '91'],
            ['id' => '9401', 'city_name' => 'KABUPATEN MERAUKE', 'province_id' => '94'],
            ['id' => '9402', 'city_name' => 'KABUPATEN JAYAWIJAYA', 'province_id' => '94'],
            ['id' => '9403', 'city_name' => 'KABUPATEN JAYAPURA', 'province_id' => '94'],
            ['id' => '9404', 'city_name' => 'KABUPATEN NABIRE', 'province_id' => '94'],
            ['id' => '9408', 'city_name' => 'KABUPATEN KEPULAUAN YAPEN', 'province_id' => '94'],
            ['id' => '9409', 'city_name' => 'KABUPATEN BIAK NUMFOR', 'province_id' => '94'],
            ['id' => '9410', 'city_name' => 'KABUPATEN PANIAI', 'province_id' => '94'],
            ['id' => '9411', 'city_name' => 'KABUPATEN PUNCAK JAYA', 'province_id' => '94'],
            ['id' => '9412', 'city_name' => 'KABUPATEN MIMIKA', 'province_id' => '94'],
            ['id' => '9413', 'city_name' => 'KABUPATEN BOVEN DIGOEL', 'province_id' => '94'],
            ['id' => '9414', 'city_name' => 'KABUPATEN MAPPI', 'province_id' => '94'],
            ['id' => '9415', 'city_name' => 'KABUPATEN ASMAT', 'province_id' => '94'],
            ['id' => '9416', 'city_name' => 'KABUPATEN YAHUKIMO', 'province_id' => '94'],
            ['id' => '9417', 'city_name' => 'KABUPATEN PEGUNUNGAN BINTANG', 'province_id' => '94'],
            ['id' => '9418', 'city_name' => 'KABUPATEN TOLIKARA', 'province_id' => '94'],
            ['id' => '9419', 'city_name' => 'KABUPATEN SARMI', 'province_id' => '94'],
            ['id' => '9420', 'city_name' => 'KABUPATEN KEEROM', 'province_id' => '94'],
            ['id' => '9426', 'city_name' => 'KABUPATEN WAROPEN', 'province_id' => '94'],
            ['id' => '9427', 'city_name' => 'KABUPATEN SUPIORI', 'province_id' => '94'],
            ['id' => '9428', 'city_name' => 'KABUPATEN MAMBERAMO RAYA', 'province_id' => '94'],
            ['id' => '9429', 'city_name' => 'KABUPATEN NDUGA', 'province_id' => '94'],
            ['id' => '9430', 'city_name' => 'KABUPATEN LANNY JAYA', 'province_id' => '94'],
            ['id' => '9431', 'city_name' => 'KABUPATEN MAMBERAMO TENGAH', 'province_id' => '94'],
            ['id' => '9432', 'city_name' => 'KABUPATEN YALIMO', 'province_id' => '94'],
            ['id' => '9433', 'city_name' => 'KABUPATEN PUNCAK', 'province_id' => '94'],
            ['id' => '9434', 'city_name' => 'KABUPATEN DOGIYAI', 'province_id' => '94'],
            ['id' => '9435', 'city_name' => 'KABUPATEN INTAN JAYA', 'province_id' => '94'],
            ['id' => '9436', 'city_name' => 'KABUPATEN DEIYAI', 'province_id' => '94'],
            ['id' => '9471', 'city_name' => 'KOTA JAYAPURA', 'province_id' => '94']
        ];

        City::upsert($cities, ["city_name"]);
    }
}
