<!doctype html>
<html>
  <head>
    <title>Iuran</title>
    <style type="text/css">
      body {
	font-family: Trebuchet MS, sans-serif;
	font-size: 15px;
	color: #444;
	margin-right: 24px;
}

h1	{
	font-size: 25px;
}
h2	{
	font-size: 20px;
}
h3	{
	font-size: 16px;
	font-weight: bold;
}
hr	{
	height: 1px;
	border: 0;
	color: #ddd;
	background-color: #ddd;
}

.app-desc {
  clear: both;
  margin-left: 20px;
}
.param-name {
  width: 100%;
}
.license-info {
  margin-left: 20px;
}

.license-url {
  margin-left: 20px;
}

.model {
  margin: 0 0 0px 20px;
}

.method {
  margin-left: 20px;
}

.method-notes	{
	margin: 10px 0 20px 0;
	font-size: 90%;
	color: #555;
}

pre {
  padding: 10px;
  margin-bottom: 2px;
}

.http-method {
 text-transform: uppercase;
}

pre.get {
  background-color: #0f6ab4;
}

pre.post {
  background-color: #10a54a;
}

pre.put {
  background-color: #c5862b;
}

pre.delete {
  background-color: #a41e22;
}

.huge	{
	color: #fff;
}

pre.example {
  background-color: #f3f3f3;
  padding: 10px;
  border: 1px solid #ddd;
}

code {
  white-space: pre;
}

.nickname {
  font-weight: bold;
}

.method-path {
  font-size: 1.5em;
  background-color: #0f6ab4;
}

.up {
  float:right;
}

.parameter {
  width: 500px;
}

.param {
  width: 500px;
  padding: 10px 0 0 20px;
  font-weight: bold;
}

.param-desc {
  width: 700px;
  padding: 0 0 0 20px;
  color: #777;
}

.param-type {
  font-style: italic;
}

.param-enum-header {
width: 700px;
padding: 0 0 0 60px;
color: #777;
font-weight: bold;
}

.param-enum {
width: 700px;
padding: 0 0 0 80px;
color: #777;
font-style: italic;
}

.field-label {
  padding: 0;
  margin: 0;
  clear: both;
}

.field-items	{
	padding: 0 0 15px 0;
	margin-bottom: 15px;
}

.return-type {
  clear: both;
  padding-bottom: 10px;
}

.param-header {
  font-weight: bold;
}

.method-tags {
  text-align: right;
}

.method-tag {
  background: none repeat scroll 0% 0% #24A600;
  border-radius: 3px;
  padding: 2px 10px;
  margin: 2px;
  color: #FFF;
  display: inline-block;
  text-decoration: none;
}

    </style>
  </head>
  <body>
  <h1>Iuran</h1>
    <div class="app-desc">No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)</div>
    <div class="app-desc">More information: <a href="https://helloreverb.com">https://helloreverb.com</a></div>
    <div class="app-desc">Contact Info: <a href="hello@helloreverb.com">hello@helloreverb.com</a></div>
    <div class="app-desc">Version: 1.0</div>
    <div class="app-desc">BasePath:/api</div>
    <div class="license-info">All rights reserved</div>
    <div class="license-url">http://apache.org/licenses/LICENSE-2.0.html</div>
  <h2>Access</h2>

  <h2><a name="__Methods">Methods</a></h2>
  [ Jump to <a href="#__Models">Models</a> ]

  <h3>Table of Contents </h3>
  <div class="method-summary"></div>
  <h4><a href="#Authetication">Authetication</a></h4>
  <ul>
  <li><a href="#login"><code><span class="http-method">post</span> /login</code></a></li>
  <li><a href="#logout"><code><span class="http-method">post</span> /logout</code></a></li>
  <li><a href="#register"><code><span class="http-method">post</span> /register</code></a></li>
  </ul>
  <h4><a href="#City">City</a></h4>
  <ul>
  <li><a href="#delete2"><code><span class="http-method">delete</span> /cities/1</code></a></li>
  <li><a href="#getAll2"><code><span class="http-method">get</span> /cities</code></a></li>
  <li><a href="#getOne2"><code><span class="http-method">get</span> /cities/1</code></a></li>
  <li><a href="#postCreate1"><code><span class="http-method">post</span> /cities</code></a></li>
  <li><a href="#putUpdate1"><code><span class="http-method">put</span> /cities/1</code></a></li>
  </ul>
  <h4><a href="#DuesTypes">DuesTypes</a></h4>
  <ul>
  <li><a href="#delete1"><code><span class="http-method">delete</span> /dues_types/12</code></a></li>
  <li><a href="#getAll1"><code><span class="http-method">get</span> /dues_types</code></a></li>
  <li><a href="#getOne1"><code><span class="http-method">get</span> /dues_types/1</code></a></li>
  <li><a href="#postCreate"><code><span class="http-method">post</span> /dues_types</code></a></li>
  <li><a href="#putUpdate"><code><span class="http-method">put</span> /dues_types/2</code></a></li>
  </ul>
  <h4><a href="#House">House</a></h4>
  <ul>
  <li><a href="#delete4"><code><span class="http-method">delete</span> /warga/houses/3</code></a></li>
  <li><a href="#getAll4"><code><span class="http-method">get</span> /warga/houses</code></a></li>
  <li><a href="#getOne4"><code><span class="http-method">get</span> /warga/houses/3</code></a></li>
  <li><a href="#postCreate3"><code><span class="http-method">post</span> /warga/houses</code></a></li>
  <li><a href="#putUpdate3"><code><span class="http-method">put</span> /warga/houses/3</code></a></li>
  </ul>
  <h4><a href="#Houses">Houses</a></h4>
  <ul>
  <li><a href="#create"><code><span class="http-method">post</span> /houses</code></a></li>
  <li><a href="#delete"><code><span class="http-method">delete</span> /houses/2</code></a></li>
  <li><a href="#getAll"><code><span class="http-method">get</span> /houses</code></a></li>
  <li><a href="#getOne"><code><span class="http-method">get</span> /houses/2</code></a></li>
  <li><a href="#update"><code><span class="http-method">put</span> /houses/2</code></a></li>
  </ul>
  <h4><a href="#Image">Image</a></h4>
  <ul>
  <li><a href="#getImage"><code><span class="http-method">get</span> /image/profile/default.jpg</code></a></li>
  <li><a href="#upload"><code><span class="http-method">post</span> /image</code></a></li>
  </ul>
  <h4><a href="#Province">Province</a></h4>
  <ul>
  <li><a href="#createProvince"><code><span class="http-method">post</span> /provinces</code></a></li>
  <li><a href="#deleteProvince"><code><span class="http-method">delete</span> /provinces/1</code></a></li>
  <li><a href="#getAllProvinces"><code><span class="http-method">get</span> /provinces</code></a></li>
  <li><a href="#getOneProvince"><code><span class="http-method">get</span> /provinces/2</code></a></li>
  <li><a href="#updateProvince"><code><span class="http-method">put</span> /provinces/1</code></a></li>
  </ul>
  <h4><a href="#Users">Users</a></h4>
  <ul>
  <li><a href="#delete3"><code><span class="http-method">delete</span> /users/1</code></a></li>
  <li><a href="#getAll3"><code><span class="http-method">get</span> /users</code></a></li>
  <li><a href="#getOne3"><code><span class="http-method">get</span> /users/1</code></a></li>
  <li><a href="#postCreate2"><code><span class="http-method">post</span> /users</code></a></li>
  <li><a href="#putUpdate2"><code><span class="http-method">put</span> /users</code></a></li>
  </ul>

  <h1><a name="Authetication">Authetication</a></h1>
  <div class="method"><a name="login"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="post"><code class="huge"><span class="http-method">post</span> /login</code></pre></div>
    <div class="method-summary">login (<span class="nickname">login</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/x-www-form-urlencoded</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->


    <h3 class="field-label">Form parameters</h3>
    <div class="field-items">
      <div class="param">email (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div><div class="param">password (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  format: int32</div>
    </div>  <!-- field-items -->


    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="logout"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="post"><code class="huge"><span class="http-method">post</span> /logout</code></pre></div>
    <div class="method-summary">Logout (<span class="nickname">logout</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>






    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="register"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="post"><code class="huge"><span class="http-method">post</span> /register</code></pre></div>
    <div class="method-summary">Register (<span class="nickname">register</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/x-www-form-urlencoded</code></li>
    </ul>




    <h3 class="field-label">Form parameters</h3>
    <div class="field-items">
      <div class="param">full_name (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div><div class="param">email (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div><div class="param">password (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  format: int32</div>
    </div>  <!-- field-items -->


    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <h1><a name="City">City</a></h1>
  <div class="method"><a name="delete2"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="delete"><code class="huge"><span class="http-method">delete</span> /cities/1</code></pre></div>
    <div class="method-summary">Delete (<span class="nickname">delete2</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="getAll2"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /cities</code></pre></div>
    <div class="method-summary">Get All (<span class="nickname">getAll2</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="getOne2"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /cities/1</code></pre></div>
    <div class="method-summary">Get One (<span class="nickname">getOne2</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="postCreate1"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="post"><code class="huge"><span class="http-method">post</span> /cities</code></pre></div>
    <div class="method-summary">Create (<span class="nickname">postCreate1</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Request body</h3>
    <div class="field-items">
      <div class="param">Body <a href="#CreateRequest">CreateRequest</a> (required)</div>

      <div class="param-desc"><span class="param-type">Body Parameter</span> &mdash;  </div>

    </div>  <!-- field-items -->

    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="putUpdate1"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="put"><code class="huge"><span class="http-method">put</span> /cities/1</code></pre></div>
    <div class="method-summary">Update (<span class="nickname">putUpdate1</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Request body</h3>
    <div class="field-items">
      <div class="param">Body <a href="#UpdateRequest">UpdateRequest</a> (required)</div>

      <div class="param-desc"><span class="param-type">Body Parameter</span> &mdash;  </div>

    </div>  <!-- field-items -->

    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <h1><a name="DuesTypes">DuesTypes</a></h1>
  <div class="method"><a name="delete1"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="delete"><code class="huge"><span class="http-method">delete</span> /dues_types/12</code></pre></div>
    <div class="method-summary">Delete (<span class="nickname">delete1</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="getAll1"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /dues_types</code></pre></div>
    <div class="method-summary">Get All (<span class="nickname">getAll1</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="getOne1"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /dues_types/1</code></pre></div>
    <div class="method-summary">Get One (<span class="nickname">getOne1</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="postCreate"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="post"><code class="huge"><span class="http-method">post</span> /dues_types</code></pre></div>
    <div class="method-summary">Create (<span class="nickname">postCreate</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/x-www-form-urlencoded</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->


    <h3 class="field-label">Form parameters</h3>
    <div class="field-items">
      <div class="param">dues_name (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div><div class="param">price (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  format: int32</div>
    </div>  <!-- field-items -->


    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="putUpdate"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="put"><code class="huge"><span class="http-method">put</span> /dues_types/2</code></pre></div>
    <div class="method-summary">Update (<span class="nickname">putUpdate</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/x-www-form-urlencoded</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->


    <h3 class="field-label">Form parameters</h3>
    <div class="field-items">
      <div class="param">dues_name (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div><div class="param">price (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  format: int32</div>
    </div>  <!-- field-items -->


    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <h1><a name="House">House</a></h1>
  <div class="method"><a name="delete4"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="delete"><code class="huge"><span class="http-method">delete</span> /warga/houses/3</code></pre></div>
    <div class="method-summary">Delete (<span class="nickname">delete4</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="getAll4"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /warga/houses</code></pre></div>
    <div class="method-summary">Get All (<span class="nickname">getAll4</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>






    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="getOne4"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /warga/houses/3</code></pre></div>
    <div class="method-summary">Get One (<span class="nickname">getOne4</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>






    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="postCreate3"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="post"><code class="huge"><span class="http-method">post</span> /warga/houses</code></pre></div>
    <div class="method-summary">Create (<span class="nickname">postCreate3</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="putUpdate3"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="put"><code class="huge"><span class="http-method">put</span> /warga/houses/3</code></pre></div>
    <div class="method-summary">Update (<span class="nickname">putUpdate3</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <h1><a name="Houses">Houses</a></h1>
  <div class="method"><a name="create"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="post"><code class="huge"><span class="http-method">post</span> /houses</code></pre></div>
    <div class="method-summary">Create (<span class="nickname">create</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/x-www-form-urlencoded</code></li>
    </ul>




    <h3 class="field-label">Form parameters</h3>
    <div class="field-items">
      <div class="param">house_name (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div><div class="param">user_id (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  format: int32</div><div class="param">picture (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div><div class="param">unit_cars (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  format: int32</div><div class="param">unit_motorcycle (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  format: int32</div><div class="param">address (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div><div class="param">city_id (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  format: int32</div>
    </div>  <!-- field-items -->


    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="delete"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="delete"><code class="huge"><span class="http-method">delete</span> /houses/2</code></pre></div>
    <div class="method-summary">Delete (<span class="nickname">delete</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="getAll"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /houses</code></pre></div>
    <div class="method-summary">Get All (<span class="nickname">getAll</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>






    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="getOne"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /houses/2</code></pre></div>
    <div class="method-summary">Get One (<span class="nickname">getOne</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="update"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="put"><code class="huge"><span class="http-method">put</span> /houses/2</code></pre></div>
    <div class="method-summary">Update (<span class="nickname">update</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/x-www-form-urlencoded</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->


    <h3 class="field-label">Form parameters</h3>
    <div class="field-items">
      <div class="param">house_name (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div><div class="param">user_id (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  format: int32</div><div class="param">unit_cars (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  format: int32</div><div class="param">unit_motorcycle (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  format: int32</div><div class="param">address (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div><div class="param">city_id (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  format: int32</div><div class="param">picture (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div>
    </div>  <!-- field-items -->


    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <h1><a name="Image">Image</a></h1>
  <div class="method"><a name="getImage"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /image/profile/default.jpg</code></pre></div>
    <div class="method-summary">Get Image (<span class="nickname">getImage</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="upload"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="post"><code class="huge"><span class="http-method">post</span> /image</code></pre></div>
    <div class="method-summary">Upload (<span class="nickname">upload</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/x-www-form-urlencoded</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->


    <h3 class="field-label">Form parameters</h3>
    <div class="field-items">
      <div class="param">image (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div>
    </div>  <!-- field-items -->


    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <h1><a name="Province">Province</a></h1>
  <div class="method"><a name="createProvince"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="post"><code class="huge"><span class="http-method">post</span> /provinces</code></pre></div>
    <div class="method-summary">Create Province (<span class="nickname">createProvince</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Request body</h3>
    <div class="field-items">
      <div class="param">Body <a href="#CreateProvinceRequest">CreateProvinceRequest</a> (required)</div>

      <div class="param-desc"><span class="param-type">Body Parameter</span> &mdash;  </div>

    </div>  <!-- field-items -->

    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="deleteProvince"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="delete"><code class="huge"><span class="http-method">delete</span> /provinces/1</code></pre></div>
    <div class="method-summary">Delete Province (<span class="nickname">deleteProvince</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="getAllProvinces"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /provinces</code></pre></div>
    <div class="method-summary">Get All Provinces (<span class="nickname">getAllProvinces</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>






    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="getOneProvince"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /provinces/2</code></pre></div>
    <div class="method-summary">Get One Province (<span class="nickname">getOneProvince</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="updateProvince"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="put"><code class="huge"><span class="http-method">put</span> /provinces/1</code></pre></div>
    <div class="method-summary">Update Province (<span class="nickname">updateProvince</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Request body</h3>
    <div class="field-items">
      <div class="param">Body <a href="#UpdateProvinceRequest">UpdateProvinceRequest</a> (required)</div>

      <div class="param-desc"><span class="param-type">Body Parameter</span> &mdash;  </div>

    </div>  <!-- field-items -->

    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <h1><a name="Users">Users</a></h1>
  <div class="method"><a name="delete3"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="delete"><code class="huge"><span class="http-method">delete</span> /users/1</code></pre></div>
    <div class="method-summary">Delete (<span class="nickname">delete3</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="getAll3"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /users</code></pre></div>
    <div class="method-summary">Get All (<span class="nickname">getAll3</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="getOne3"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /users/1</code></pre></div>
    <div class="method-summary">Get One (<span class="nickname">getOne3</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="postCreate2"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="post"><code class="huge"><span class="http-method">post</span> /users</code></pre></div>
    <div class="method-summary">Create (<span class="nickname">postCreate2</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/x-www-form-urlencoded</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->


    <h3 class="field-label">Form parameters</h3>
    <div class="field-items">
      <div class="param">full_name (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div><div class="param">email (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  </div><div class="param">password (required)</div>

      <div class="param-desc"><span class="param-type">Form Parameter</span> &mdash;  format: int32</div>
    </div>  <!-- field-items -->


    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="putUpdate2"/>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="put"><code class="huge"><span class="http-method">put</span> /users</code></pre></div>
    <div class="method-summary">Update (<span class="nickname">putUpdate2</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>


    <h3 class="field-label">Request headers</h3>
    <div class="field-items">
      <div class="param">Authorization (optional)</div>

      <div class="param-desc"><span class="param-type">Header Parameter</span> &mdash;  default: Bearer {token} </div>
    </div>  <!-- field-items -->




    <!--Todo: process Response Object and its headers, schema, examples -->


    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>

  <h2><a name="__Models">Models</a></h2>
  [ Jump to <a href="#__Methods">Methods</a> ]

  <h3>Table of Contents</h3>
  <ol>
    <li><a href="#CreateProvinceRequest"><code>CreateProvinceRequest</code> - CreateProvinceRequest</a></li>
    <li><a href="#CreateRequest"><code>CreateRequest</code> - CreateRequest</a></li>
    <li><a href="#UpdateProvinceRequest"><code>UpdateProvinceRequest</code> - UpdateProvinceRequest</a></li>
    <li><a href="#UpdateRequest"><code>UpdateRequest</code> - UpdateRequest</a></li>
  </ol>

  <div class="model">
    <h3><a name="CreateProvinceRequest"><code>CreateProvinceRequest</code> - CreateProvinceRequest</a> <a class="up" href="#__Models">Up</a></h3>
    <div class='model-description'></div>
    <div class="field-items">
      <div class="param">province_name </div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  </div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="CreateRequest"><code>CreateRequest</code> - CreateRequest</a> <a class="up" href="#__Models">Up</a></h3>
    <div class='model-description'></div>
    <div class="field-items">
      <div class="param">province_id </div><div class="param-desc"><span class="param-type"><a href="#integer">Integer</a></span>  format: int32</div>
<div class="param">city_name </div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  </div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="UpdateProvinceRequest"><code>UpdateProvinceRequest</code> - UpdateProvinceRequest</a> <a class="up" href="#__Models">Up</a></h3>
    <div class='model-description'></div>
    <div class="field-items">
      <div class="param">province_name </div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  </div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="UpdateRequest"><code>UpdateRequest</code> - UpdateRequest</a> <a class="up" href="#__Models">Up</a></h3>
    <div class='model-description'></div>
    <div class="field-items">
      <div class="param">city_name </div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  </div>
<div class="param">province_id </div><div class="param-desc"><span class="param-type"><a href="#integer">Integer</a></span>  format: int32</div>
    </div>  <!-- field-items -->
  </div>
  </body>
</html>
